name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Environment
        run: |
          echo "CI=$CI"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
          echo "Hostname: $(hostname)"
          go version
          uname -a
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
