name: Self Test
on: push
jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - name: Go vet
        run: go vet ./...
  test:
    runs-on: ubuntu-latest
    needs: vet
    steps:
      - name: Run tests
        run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: vet
    steps:
      - name: Build binary
        run: go build -o bin/athanor ./cmd/athanor
